### ISSUE TITLE
decimate factor on finite sources - decide if it is save now

### ISSUE THREAD

**Issue by emolch** [pyrocko/grond#10]

**Comment by miili** [comment]
Alright: atm the discretisation is not checked against the sub-source spacing. Discretisation is applied for `Target` and `StaticTarget`.

Our master plan is to decide automatically and adaptive for a safe discretisation. Yet, for now we could disable decimation for waveforms targets completely?

**Comment by emolch** [comment]
- [ ] change setting in insar example (2 ok?)
- [ ] add warning
- [ ] improve description

**Comment by emolch** [comment]
description has been update in Pyrocko df0769896c1ecf3ccb5b36b93ade04d7ddfc3bf9
