### ISSUE TITLE
Station plot

### ISSUE THREAD

**Issue by emolch** [pyrocko/grond#12]

**Comment by emolch** [comment]
- one symbol per line in legend
- description text
- labels overlap - how fix? remove all labels?
- in regional mt example, I see a red point (excluded) but it appears in the contributions, how can be?

**Comment by miili** [comment]
>     * one symbol per line in legend
Can you elaborate on this, currently there is one circle per line, max 5 lines.

>     * labels overlap - how fix? remove all labels?
The plot becomes quite messy when many stations are present. We can avoid collisions and use smaller fonts. Yet I am not sure whether this fill do it with 30+ stations

>     * in regional mt example, I see a red point (excluded) but it appears in the contributions, how can be?
When `cumulative_weight` is `nan` the station is marked as red. Will look into this.

**Comment by emolch** [comment]
> one symbol per line in legend

this seems to be matplotlib version dependent, I try to fix it...

**Comment by emolch** [comment]
Contributions plotting is partially fixed in c25ded5c1fcccb65d7d9c49569dc03a1ae0eb20d

I also changed to group the plots according to path/component rather than only path because we sometimes have multiple targets per station in a single path (eg. `rayleigh.*.R` and `rayleigh.*.Z`).

But it will not yet work when we have multi-misifit targets in between. The target-to-index lookup will have to be fixed for that. Also I doubt that the contribution bars on the waveform plots are then shown correctly. I will work on this tomorrow.

**Comment by miili** [comment]
Refactored and added GNSS distrubtion plots, mean component weight is shown.

For the multi-misfit target we can reuse code from `ContributionPlot`.
Guess we have to optimise for best label position, should not be hard to accomplish.

**Comment by emolch** [comment]
TBD:
- excluded: change color from red to gray or open symbol
- have a first plot already before optimisation
- item title is not shown in html
