### ISSUE TITLE
Automatic tests

### ISSUE THREAD

**Issue by emolch** [pyrocko/grond#17]
- run all examples
  - reports before
  - run check
  - run go
  - reports during run
  - run harvest
  - run cluster
  - run report (in parallel)
- add example with joint optimisation (Laquila?)
- add GNSS example (mayotte, deflation source)
- add second event to regional surfacewave example (to test reports with more than one event, parallel, etc)

**Comment by miili** [comment]
Discuss unittests.

**Comment by emolch** [comment]
Test coverage is now at 73%.
